/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// define variables del sistema
uint8_t dummy_8bit = 0;
uint16_t dummy_16bit = 0;
uint32_t dummy_32bit = 0;

uint16_t dummy_16bit_dec = 0;
uint16_t dummy_16bit_hex = 0;
uint16_t dummy_16bit_bin = 0;

uint8_t overflow_demo = 0;

uint8_t a = 0;
int8_t b = 0;
int8_t c = 0;

// headers

int main(void)
{
	dummy_8bit = 0b11001010;
	dummy_16bit = 4550;
	dummy_32bit = 1234547458;

	dummy_16bit_dec = 32;
	dummy_16bit_hex = 0x20;
	dummy_16bit_bin = 0b100000;

	dummy_16bit_bin = dummy_16bit_bin << 4;
	dummy_16bit_bin = dummy_16bit_bin >> 5;

	//exponiendo overflow
	dummy_8bit = 255;
	dummy_16bit = 255;
	dummy_32bit = 255;

	overflow_demo = dummy_8bit + 1;
	overflow_demo = overflow_demo + 1;
	// overflow_demo = 735;

	a = 200;
	b = 200;
	c = -1;


    /* Loop forever */
	while(1);
}

// funciones
