/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// define variables

uint8_t dummy_8bit = 0;
uint16_t dummy_16bit = 0;
uint32_t dummy_32bit = 0;

uint16_t dummy_16bit_dec = 0;
uint16_t dummy_16bit_hex = 0;
uint16_t dummy_16bit_bin = 0;

uint8_t overflow_demo = 0;

// exercise 0.4 variables
uint8_t a = 0;
int8_t b = 0;
int8_t c = 0;

// exercise 0.5 variables
int8_t x = 0;
uint8_t y = 0;
int8_t max8bit = INT8_MAX;
int8_t min8bit = INT8_MIN;
uint8_t maxu8bit = UINT8_MAX;
uint16_t maxu16bit = UINT16_MAX;

// exercise 0.6 variables
uint8_t result;

// exercise 0.7 variables
uint8_t x_07 = 0;

// exercise 0.8 variables
uint8_t a_08 = 0;
uint8_t b_08 = 0;
uint8_t c_08 = 0;
uint8_t r1 = 0;
uint8_t r2 = 0;
uint8_t r3 = 0;
uint8_t r4 = 0;
uint8_t r5 = 0;

// exercise 1.1 variables
uint8_t a_11 = 17;
uint8_t b_11 = 5;
uint8_t div_result = 0;
uint8_t mod_result = 0;
uint8_t mul_result = 0;

// exercise 1.2 variables
uint8_t x_12 = 200;
uint8_t y_12 = 100;
uint8_t sum = 0;

// exercise 1.3 variables
uint8_t val = 3;
uint8_t left1 = 0;
uint8_t left2 = 0;
uint8_t left3 = 0;
uint8_t right1 = 0;

// exercise 1.4 variables
uint8_t if_value1 = 0;
uint8_t if_value2 = 1;
uint8_t if_value3 = 2;
uint8_t if_result = 0;

// exercise 1.5 variables
uint8_t counter_15 = 0;

// exercise 1.6 variables
uint8_t sum_16 = 0;
uint8_t counter_16 = 0;
uint16_t bigsum_16 = 0;
uint8_t bigcounter_16 = 0;

// exercise 1.7 variables
uint8_t result_17 = 0;

// exercise 1.8 variables
uint8_t input = 0;
uint8_t output = 0;


// headers

int main(void)
{
	dummy_8bit = 0b11001010;
	dummy_16bit = 4550;
	dummy_32bit = 1234547458;

	dummy_16bit_dec = 32;
	dummy_16bit_hex = 0x20;
	dummy_16bit_bin = 0b100000;

	dummy_16bit_bin = dummy_16bit_bin << 4;
	dummy_16bit_bin = dummy_16bit_bin >> 5;

	// overflow
	dummy_8bit = 255;
	dummy_16bit = 255;
	dummy_32bit = 255;

	overflow_demo = dummy_8bit + 1;
	overflow_demo = overflow_demo + 1;
	overflow_demo = 735;

	// exercise 0.4
	a = 200;	// prediction a = 200
	b = 200;	// prediction b = -56; it uses 2's complement
	c = -1;		// prediction c = -1; 0xff in hex = 0b11

	// exercise 0.5
	x = 127;
	x += 1;		// x overflows x = -128 because it is signed

	y = 255;
	y += 1;		// y overflows y = 0 because it is unsigned

	// exercise 0.6
	result = 0x0f + 0x01;	// prediction result = 0x10; doesn't overflow
	result = 0xff + 0x01;	// prediction result = 0x00; overflow, oxff = 0b11111111
	result = 0xa0 + 0x5f;	// prediction result = 0xff; doesn't overflow
	result = 0xa0 + 0x60;	// prediction result = 0x00; overflow, if it were a uint16_t result = 0x0100;

	// exercise 0.7
	x_07 = 0x01;
	x_07 = 0x02;
	x_07 = 0x04;
	x_07 = 0x08;
	x_07 = 0x10;
	x_07 = 0x20;
	x_07 = 0x40;
	x_07 = 0x80;

	// exercise 0.8
	a_08 = 5;
	b_08 = 0;
	c_08 = 255;
	r1 = !a_08;		// prediction a = 0
	r2 = !b_08;		// prediction b = 1
	r3 = !c_08;		// prediction c = 0
	r4 = ~c_08;		// prediction ~c = ~(0b11111111) = 0
	r5 = ~a_08;		// prediction ~a = ~(0b00000101) = 0b11111010 = 250

	// exercise 1.1
	div_result = a_11 / b_11;		// prediction = 3
	mod_result = a_11 % b_11;		// prediction = 2
	mul_result = a_11 * b_11;		// prediction = 85

	// exercise 1.2
	sum = x_12 + y_12;		// prediction = 44

	// exercise 1.3
	left1 = val << 1;		// prediction = (0b00000011) << 1 = (0b00000110) = 6
	left2 = val << 2;		// prediction = (0b00000011) << 2 = (0b00001100) = 12
	left3 = val << 3;		// prediction = (0b00000011) << 3 = (0b00011000) = 24
	right1 = val >> 1;		// prediction = (0b00000011) >> 1 = (0b00000001) = 1

	// exercise 1.4
	if (if_value1)
	{
		if_result = 0xff;
	}
	if (if_value2)
	{
		if_result = if_value2;
	}
	else if (if_value3 == 2) {

	}
	{
		if_result = 123;
	}

	// exercise 1.5
	for (uint8_t i = 0; i < 9; i++)
	{
		counter_15++;
	}
	counter_15 = 0;
	for (uint8_t i = 0; i < 9; i++)
	{
		counter_15 += 2;
	}
	counter_15 = 0;
	for (uint8_t i = 10; i > 0; i--)
	{
		counter_15 = i;
	}
	counter_15 = 0;
	for (uint8_t i = 0; i < 100; i++)
	{
		counter_15++;
		if (counter_15 == 30)
		{
			break;
		}
	}

	// exercise 1.6
	while (counter_16 != 10)
	{
		counter_16++;
		sum_16 = sum_16 + counter_16;
	} // predicted result = 55

	while (bigcounter_16 != 100)
	{
		bigcounter_16++;
		bigsum_16 = bigsum_16 + bigcounter_16;
	} // predicted result = 5050

	// exercise 1.7
	while (0)
	{
		result_17 = 42;
	}

	do {
		result_17 = 42;
	} while (0);	// the do-while executes at least once, even if the condition is false

	// exercise 1.8
	switch (input) {
		case 0:
		{
			output = input;
//			break;
		}
		case 1:
		{
			output = input;
//			break;
		}
		case 2:
		{
			output = input;
			break;
		}
		case 3:
		{
			output = input;
			break;
		}
		default:
			output = 123;
			break;
	}

    /* Loop forever */
	while(1);
}

// funciones
